# fly.toml app configuration file generated for wispy-wind-734 on 2023-09-06T15:48:48-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-wind-734"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
